services:
  nginx:
    image: nginx:alpine
    container_name: gestor-de-proyectos-ti-nginx-pruebas3
    restart: always
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network-pruebas3

  backend:
    build:
      context: ./backend_v2
      dockerfile: Dockerfile
    container_name: gestor-de-proyectos-ti-backend-pruebas3
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db:${DB_PORT:-5432}/${DB_NAME:-project_manager}
      - ERP_DATABASE_URL=${ERP_DATABASE_URL}
      - ENVIRONMENT=pruebas3
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - APP_VERSION=${APP_VERSION:-v2.2.0-DEV}
      - FRONTEND_URL=http://${FRONTEND_HOST:-localhost}
      - TZ=America/Bogota
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
    networks:
      - app-network-pruebas3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api/v2
    container_name: gestor-de-proyectos-ti-frontend-pruebas3
    restart: always
    environment:
      - VITE_API_BASE_URL=/api/v2
    depends_on:
      - backend
    networks:
      - app-network-pruebas3

  db:
    image: postgres:15-alpine
    container_name: gestor-de-proyectos-ti-db-pruebas3
    restart: always
    volumes:
      - postgres_data_pruebas3:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-project_manager}
      - TZ=America/Bogota
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    ports:
      - "5435:5432"
    networks:
      - app-network-pruebas3

networks:
  app-network-pruebas3:
    driver: bridge

volumes:
  postgres_data_pruebas3:
