services:
  #  nginx:
  #    image: nginx:alpine
  #    container_name: gestor-de-proyectos-ti-nginx
  #    ports:
  #      - "80:80"
  #    volumes:
  #      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    depends_on:
  #      - frontend
  #      - backend
  #    networks:
  #      - app-network

  backend:
    build:
      context: ./backend_v2
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Re-expuesto para acceso directo por IP:8000
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db:${DB_PORT:-5432}/${DB_NAME:-project_manager}
      - APP_VERSION=v2.1.0-DEV
      - ERP_DATABASE_URL=${ERP_DATABASE_URL}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - FRONTEND_URL=http://${FRONTEND_HOST:-localhost}
      - TZ=America/Bogota
    volumes:
      - ./backend_v2:/app
    depends_on:
      - db
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2 # Modo Produccion
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # Modo Desarrollo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173" # Re-expuesto para acceso directo por IP:5173
    environment:
      # URL RELATIVA: Permite que funcione por IP o por Dominio automáticamente a través de Nginx (puerto 80)
      - VITE_API_BASE_URL=/api/v2
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: gestor-de-proyectos-ti-adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: gestor-de-proyectos-ti-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-project_manager}
      - TZ=America/Bogota
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432" # Re-expuesto para mantenimiento
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
